Script started on 2015年03月17日 (週二) 11時03分16秒
]0;F74027036@2015cpp: ~F74027036@2015cpp:~$ who [Kami
F74027036
]0;F74027036@2015cpp: ~F74027036@2015cpp:~$ pwd
/home/F74027036
]0;F74027036@2015cpp: ~F74027036@2015cpp:~$ git config -l
user.name=supertrens
user.email=trens552@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
]0;F74027036@2015cpp: ~F74027036@2015cpp:~$ git config -lpwd[Kwhoamigit clone https://github.com/supertrens/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;F74027036@2015cpp: ~F74027036@2015cpp:~$ exit

Script done on 2015年03月17日 (週二) 11時04分12秒
